import * as Clipboard from "expo-clipboard";
import * as Linking from "expo-linking";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export interface StatementRow {
  date: string;
  ref: string;
  user: string;
  status: string;
  items: number;
  amount: number;
}

export interface EarningsMonthRow {
  label: string; // e.g. "Aug 2026"
  key: string; // "2026-08" for sorting
  shipments: number;
  units: number;
  amount: number;
}

const money = (n: number) => `₹ ${Math.round(n).toLocaleString("en-IN")}`;

const statusColor = (s: string) =>
  s === "received" ? "#16A34A" : s === "pending" ? "#D97706" : "#2563EB";

const DOC_CSS = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; color: #111827; padding: 32px; }
  .brand { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 3px solid #2F80ED; padding-bottom: 12px; margin-bottom: 20px; }
  .brand h1 { font-size: 22px; letter-spacing: -0.3px; }
  .brand .sub { color: #6B7280; font-size: 12px; margin-top: 3px; }
  .brand .logo { color: #2F80ED; font-weight: 800; font-size: 18px; letter-spacing: 0.5px; }
  .meta { color: #6B7280; font-size: 12px; margin-bottom: 18px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; background: #F3F4F6; padding: 8px 10px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.6px; color: #374151; border-bottom: 2px solid #E5E7EB; }
  td { padding: 8px 10px; border-bottom: 1px solid #F3F4F6; }
  td.num, th.num { text-align: right; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 10px; font-weight: 700; color: #fff; }
  .totals { margin-top: 18px; display: flex; justify-content: flex-end; }
  .totals-inner { border: 1px solid #E5E7EB; border-radius: 10px; padding: 12px 18px; font-size: 13px; }
  .totals-inner div { display: flex; justify-content: space-between; gap: 40px; padding: 3px 0; }
  .totals-inner .grand { font-weight: 800; font-size: 15px; border-top: 1px solid #E5E7EB; margin-top: 6px; padding-top: 8px; }
  .footer { margin-top: 28px; color: #9CA3AF; font-size: 10px; text-align: center; }
  @media print { body { padding: 16px; } }
`;

function docShell(title: string, subtitle: string, meta: string, body: string) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>${DOC_CSS}</style></head>
  <body>
    <div class="brand">
      <div><h1>${title}</h1><div class="sub">${subtitle}</div></div>
      <div class="logo">MasalaFlow</div>
    </div>
    <div class="meta">${meta}</div>
    ${body}
    <div class="footer">Generated by MasalaFlow · ${new Date().toLocaleString("en-GB")}</div>
  </body></html>`;
}

// Printable shipment-log statement (used by Shipment Logs export).
export function buildStatementHtml(opts: {
  rows: StatementRow[];
  periodLabel: string;
  showUser: boolean;
  ownerName?: string;
}) {
  const { rows, periodLabel, showUser, ownerName } = opts;
  const totalItems = rows.reduce((a, r) => a + r.items, 0);
  const totalAmount = rows.reduce((a, r) => a + r.amount, 0);

  const head = `<tr>
    <th>Date</th><th>Shipment</th>${showUser ? "<th>User</th>" : ""}
    <th>Status</th><th class="num">Items</th><th class="num">Value</th>
  </tr>`;

  const body = rows
    .map(
      (r) => `<tr>
      <td>${r.date}</td>
      <td>${r.ref}</td>
      ${showUser ? `<td>${r.user}</td>` : ""}
      <td><span class="badge" style="background:${statusColor(r.status.toLowerCase())}">${r.status}</span></td>
      <td class="num">${r.items}</td>
      <td class="num">${money(r.amount)}</td>
    </tr>`,
    )
    .join("");

  const html = `<table><thead>${head}</thead><tbody>${body}</tbody></table>
  <div class="totals"><div class="totals-inner">
    <div><span>Shipments</span><span>${rows.length}</span></div>
    <div><span>Total items</span><span>${totalItems}</span></div>
    <div class="grand"><span>Total value</span><span>${money(totalAmount)}</span></div>
  </div></div>`;

  return docShell(
    "Shipment Statement",
    periodLabel,
    `${ownerName ? `For: ${ownerName} · ` : ""}${rows.length} shipments`,
    html,
  );
}

// Printable earnings summary (used by My Earnings export).
export function buildEarningsHtml(opts: {
  months: EarningsMonthRow[];
  ratePerUnit: number;
  ownerName?: string;
}) {
  const { months, ratePerUnit, ownerName } = opts;
  const totalShipments = months.reduce((a, m) => a + m.shipments, 0);
  const totalUnits = months.reduce((a, m) => a + m.units, 0);
  const totalAmount = months.reduce((a, m) => a + m.amount, 0);

  const head = `<tr><th>Month</th><th class="num">Shipments</th><th class="num">Units</th><th class="num">Earnings</th></tr>`;
  const body = months
    .map(
      (m) => `<tr>
      <td>${m.label}</td>
      <td class="num">${m.shipments}</td>
      <td class="num">${m.units}</td>
      <td class="num">${money(m.amount)}</td>
    </tr>`,
    )
    .join("");

  const html = `<table><thead>${head}</thead><tbody>${body}</tbody></table>
  <div class="totals"><div class="totals-inner">
    <div><span>Payout rate</span><span>${money(ratePerUnit)} / unit</span></div>
    <div><span>Shipments</span><span>${totalShipments}</span></div>
    <div><span>Total units</span><span>${totalUnits}</span></div>
    <div class="grand"><span>Total earnings</span><span>${money(totalAmount)}</span></div>
  </div></div>`;

  return docShell(
    "Earnings Statement",
    "Monthly payout summary",
    `${ownerName ? `For: ${ownerName} · ` : ""}${months.length} months covered`,
    html,
  );
}

const csvEscape = (v: string | number) => {
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

export function statementToCsv(rows: StatementRow[], showUser: boolean): string {
  const header = ["Date", "Shipment", ...(showUser ? ["User"] : []), "Status", "Items", "Value"];
  const lines = rows.map((r) =>
    [
      r.date,
      r.ref,
      ...(showUser ? [r.user] : []),
      r.status,
      r.items,
      r.amount,
    ]
      .map(csvEscape)
      .join(","),
  );
  return [header.join(","), ...lines].join("\n");
}

export function earningsToCsv(months: EarningsMonthRow[]): string {
  const header = "Month,Shipments,Units,Earnings";
  const lines = months.map((m) =>
    [m.label, m.shipments, m.units, m.amount].map(csvEscape).join(","),
  );
  return [header, ...lines].join("\n");
}

// Generates the PDF in cache and opens the native share sheet.
// Returns false when generation/sharing is unavailable (e.g. web).
export async function sharePdf(
  html: string,
  dialogTitle = "Share statement",
): Promise<boolean> {
  try {
    const { uri } = await Print.printToFileAsync({ html });
    if (!(await Sharing.isAvailableAsync())) return false;
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      UTI: "com.adobe.pdf",
      dialogTitle,
    });
    return true;
  } catch (error) {
    console.error("sharePdf failed:", error);
    return false;
  }
}

export async function copyText(text: string): Promise<boolean> {
  try {
    await Clipboard.setStringAsync(text);
    return true;
  } catch (error) {
    console.error("copyText failed:", error);
    return false;
  }
}

// Opens WhatsApp with the text pre-filled. Prefers the native app scheme;
// falls back to wa.me (browser WhatsApp) when the app isn't installed.
// Returns false when neither can be opened (e.g. web).
export async function shareTextToWhatsApp(text: string): Promise<boolean> {
  const encoded = encodeURIComponent(text);
  try {
    const appUrl = `whatsapp://send?text=${encoded}`;
    const canOpenApp = await Linking.canOpenURL(appUrl);
    if (canOpenApp) {
      await Linking.openURL(appUrl);
      return true;
    }
    // No WhatsApp app — use the universal wa.me link.
    await Linking.openURL(`https://wa.me/?text=${encoded}`);
    return true;
  } catch (error) {
    console.error("shareTextToWhatsApp failed:", error);
    return false;
  }
}
